export const communityAdjectives = {
  'wealthProsperity': `$["an industrious", "a hardworking", "a productive", "a commerce-oriented", "a wealthy", "a prosperous", "an affluent", "a dedicated"]`,
  'generosityCharity': `$["a generous", "a caring", "a kindly", "a charitable", "an accommodating", "an altrusitic", "a magnanimous", "a giving", "a benevolent"]`,
  'religiousPietyDevotion': `$["a religious", "a pious", "a spiritually-devoted", "a devoted", "a clerical", "a devout", "a sectarian", "a blessed", "a sacred"]`,
  'knowledgeDiscovery': `$["a knowledgeable", "an inventive", "an insightful", "an analytical", "a thoughtful", "a knowledge-oriented", "a discovery-obsessed", "an advanceed"]`,
  'disciplineTraining': `$["a well-disciplined", "a highly-disciplined", "a regimented", "a regulated", "a training-focused", "a controlled", "a uniform", "a strict"]`,
  'hospitalityCommunity': `$["a tight-knit", "a hospitable", "a congenial", "an open", "a cordial", "a neighborly", "a loquacious", "a welcoming", "a warm"]`,
  'compassionAnimalHusbandry': `$["a compassionate", "a nurturing", "a caretaking", "a tending", "a herding", "a shepherding", "a connected", "a gentle"]`,
  'individualityOpportunism': `$["an individualistic", "an opportunistic", "a self-absorbed", "a selfish", "a hardened", "a cosmopolitan", "a cynical", "a competitive"]`,
  'innovationExperimentation': `$["a practiced", "an investigative", "an innovative", "an empirical", "a trial-oriented", "an ingenious", "an original", "a visionary"]`,
  'curiousityExploration': `$["a curious", "an interested", "an explorative", "an inquisitive", "a nosy", "a meddlesome", "an intrusive", "an observant"]`,
  'authoritarianismSpectacle': `$["an authoritarian", "a heavily-patrolled", "an autocratic", "an imperious", "a ceremonious", "a strictly-governed", "an isolationist", "an ordered"]`,
  'acquisitionEnterprise': `$["an enterprising", "an aquisitional", "a wealth-focused", "a possessive", "a controlling", "a proprietary", "a segmented", "a volatile"]`,
  'creationExpression': `$["a creative", "an expressive", "an artistic", "a dramatic", "a musical", "a prolific", "an endowed", "a colorful", "a passionate", "an energetic"]`,
  'craftsmanshipStatus': `$["a crafty", "a meticulous", "an architectural", "an engineered", "a stratified", "a project-focused", "a clever", "a technical", "an adroit"]`,
  'animismRitual': `$["an animistic", "a ritualistic", "a spiritualistic", "a pre-Thelean", "an etherial", "a devotional", "an antiquated", "a historic", "a superstitious"]`,
  'hierarchyEducation': `$["a hierarchical", "a learned", "an enlightened", "a scholarly", "a well-read", "an academic", "an erudite", "an elitist", "a privileged"]`,
  'communityGrowthCommerce': `$["a commerce-oriented", "a merchant", "a trading", "a mercantile", "a surplus", "a bartering", "a profitable", "a bargaining"]`,
  'selfRelianceAutonomy': `$["an autonomous", "a loose", "an expedient", "an unusual", "a remote", "a confined", "a resourceful", "a challenging", "an unforgiving"]`,
  'dutyService': `$["a dutiful", "a service-oriented", "a conscientious", "a diligent", "a fastidious", "a compulsory", "an obedient", "a rigorous", "law abiding"]`,
  'ancestryLocalHistory': `$["a heralded", "a historical", "a storied", "a well-storied", "a reverent", "a venerable", "a deeply rooted"]`
}