/* Remapping Home Community based on biome and region

  'caretakers and healers': [],
  'cultists and mystics': [],
  'entertainers and artists': [],
  'farmers and fishers': [],
  'gardeners and shepherds': [],
  'guardians and sellswords': [],
  'laborers and servants': [],
  'dyers and weavers': [],
  'paupers and beggars': [],
  'veterans and enforcers': [],
  'fortune tellers and diviners': [],
  'dock workers and cargo haulers': [],
  'artisans and makers': [],
  'intellectuals and architects': [],
  'luminaries and nobles': [],
  'merchants and curio peddlers': [],
  'philosophers and scholars': [],
  'curio traders and smugglers': [],
  'traders and innkeepers': [],
  'travelers and adventurers': []

*/

export const communityTypesGeneric = {
  'caretakers and healers': [],
  'cultists and mystics': [],
  'entertainers and artists': [],
  'farmers and fishers': [],
  'gardeners and shepherds': [],
  'guardians and sellswords': [],
  'laborers and servants': [],
  'dyers and weavers': [],
  'paupers and beggars': [],
  'veterans and enforcers': [],
  'fortune tellers and diviners': [],
  'dock workers and cargo haulers': [],
  'artisans and makers': [],
  'intellectuals and architects': [],
  'luminaries and nobles': [],
  'merchants and curio peddlers': [],
  'philosophers and scholars': [],
  'curio traders and smugglers': [],
  'traders and innkeepers': [],
  'travelers and adventurers': []
}

export const communityTypesBiomeSpecific = {
/*--- the Ommultic Front ---*/
  'spruce forests': {
    'caretakers and healers': [`$["", "", ""]`],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'expansive tundra': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'cold lakefronts': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
/*--- central Wendajii ---*/
  'savannah grasslands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'rolling storm plains': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'grassy hills': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
/*--- the Brolean Expanse ---*/
  "temperate rainforests": {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'woodlands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'fen glades': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
/*--- Delonian Hinn ---*/
  'deep forest riverlands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'meadowlands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'mossy shale valleys': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
/*--- New Scorth ---*/
  'craggy northlands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'central farmlands': {
      phrases: {
            'caretakers and healers': [],
            'cultists and mystics': [],
            'entertainers and artists': [],
            'farmers and fishers': [],
            'gardeners and shepherds': [],
            'guardians and sellswords': [],
            'laborers and servants': [],
            'dyers and weavers': [],
            'paupers and beggars': [],
            'veterans and enforcers': [],
            'fortune tellers and diviners': [],
            'dock workers and cargo haulers': [],
            'artisans and makers': [],
            'intellectuals and architects': [],
            'luminaries and nobles': [],
            'merchants and curio peddlers': [],
            'philosophers and scholars': [],
            'curio traders and smugglers': [],
            'traders and innkeepers': [],
            'travelers and adventurers': []
        },
    },
  'southern wetlands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
/*--- the Weyell North ---*/
  'northern temperate hills': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'forest groves': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'lakelands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
/*--- Northern Valadagal ---*/
  'cloudless hot deserts': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'lush southern dunes': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'clay fields': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
/*--- Mainland Schelk ---*/
  'warm woodlands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'overcast gardens': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'rice paddies': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
/*--- New Voland ---*/
  'redwoods': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'hilly expanses': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'mild shrublands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
/*--- the Djenndan Protectorate ---*/
  'wide plains and foothills': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'temperate steppes': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'farmlands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
/*--- coastal Bosen ---*/
  'olive forests': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'nut groves': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'mild coastlands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'balmy seas': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
/*--- Siadagal ---*/
  'lush farmlands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'fields': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'rainy coasts': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'summer storms': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
/*--- the forests of Creona ---*/
  'stormy woodlands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'rocky coasts': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'lush river valleys': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
/*--- Plenith South ---*/
  'tropical coasts and forests': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'rainforests': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'palm fields': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
/*--- Reviak Proper ---*/
  'steppes': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'flatlands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'lightning stormlands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'sandy plains': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
/*--- the Weyell Groves ---*/
  'temperate wetlands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'pine thrushes': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'swamps': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'mangroves': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
/*--- southwest Hinn ---*/
  'coastal wetlands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'southern flatlands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'eastern borderlands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
/*--- the Schelk Islands ---*/
  'warm inlets': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'volcanic crags': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'coral reefs': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'sandy beaches': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
/*--- central Bosen ---*/
  'rocky highlands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'river valleys': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'terraced vine fields': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
/*--- the Northern Wilds ---*/
  'icy steppes': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'extreme hills': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'frozen forests': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  },
  'wastelands': {
    'caretakers and healers': [],
    'cultists and mystics': [],
    'entertainers and artists': [],
    'farmers and fishers': [],
    'gardeners and shepherds': [],
    'guardians and sellswords': [],
    'laborers and servants': [],
    'dyers and weavers': [],
    'paupers and beggars': [],
    'veterans and enforcers': [],
    'fortune tellers and diviners': [],
    'dock workers and cargo haulers': [],
    'artisans and makers': [],
    'intellectuals and architects': [],
    'luminaries and nobles': [],
    'merchants and curio peddlers': [],
    'philosophers and scholars': [],
    'curio traders and smugglers': [],
    'traders and innkeepers': [],
    'travelers and adventurers': []
  }
}