export const communityAdjectives = {
  'wealthProsperity': `$["an industrious"]`,
  'generosityCharity': `$["a generous", "a caring", "a kindly"]`,
  'religiousPietyDevotion': `$["a religious", "a pious"]`,
  'knowledgeDiscovery': `$["an innovative"]`,
  'disciplineTraining': `$["a well-disciplined"]`,
  'hospitalityCommunity': `$["a tight-knit", "a hospitable"]`,
  'compassionAnimalHusbandry': `$["a compassionate"]`,
  'individualityOpportunism': `$["an individualistic"]`,
  'innovationExperimentation': `$["an innovative"]`,
  'curiousityExploration': `$["a curious"]`,
  'authoritarianismSpectacle': `$["an authoritarian"]`,
  'acquisitionEnterprise': `$["an enterprising"]`,
  'creationExpression': `$["a creative", "an expressive", "an artistic"]`,
  'craftsmanshipStatus': `$["a crafty", "a meticulous"]`,
  'animismRitual': `$["an animistic", "a ritualistic"]`,
  'hierarchyEducation': `$["a hierarchical", "a learned"]`,
  'communityGrowthCommerce': `$["a commerce-oriented"]`,
  'selfRelianceAutonomy': `$["an autonomous", "a loose"]`,
  'dutyService': `$["a dutiful", "a service-oriented"]`,
  'ancestryLocalHistory': `$[]`,
}