export const culturalValues = [
  'wealth and prosperity',
  'generosity and charity',
  'religious piety and devotion',
  'knowledge and discovery',
  'discipline and training',
  'hospitality and community',
  'compassion and animal husbandry',
  'individuality and opportunism',
  'innovation and experimentation',
  'curiousity and exploration',
  'autoritarianism and spectacle',
  'acquisition and enterprise',
  'creation and expression',
  'craftsmanship and status',
  'animism and ritual',
  'hierarchy and education',
  'community growth and commerce',
  'self-reliance and autonomy',
  'duty and service',
  'ancestry and local history',
];
